### ISSUE TITLE
Integration with Raster Prop Manager not Working

### ISSUE THREAD

**Issue by MeadeRobert** [linuxgurugamer/EngineIgnitor#6]
The mod's installation is not detected by the latest version of RPM.

**Comment by MeadeRobert** [comment]
What version of KSP is this version of EngineIgnitor supposed to work with?

**Comment by linuxgurugamer** [comment]
1.3.1, as it says in the OP.
But, this has nothing to do with RPM.

**Comment by MeadeRobert** [comment]
how does this have nothing to do with RPM? RPM is supposed to integrate Engine Ignitor into one of the panels.

**Comment by MOARdV** [comment]
@linuxgurugamer  - Engine Ignitor at one time included an EngineIgnitorRPM module that enabled the EI page in RasterPropMonitor.  That module was never a part of RPM.  Since I've never used EI, I don't know when that module was removed from EI, or what's changed that caused the module to disappear.
