### ISSUE TITLE
Give option to lower ullage force by engine/ lower globally

### ISSUE THREAD

**Issue by Rock3tman** [linuxgurugamer/EngineIgnitor#8]
I was revising configs for the Bluedog Design Bureau mod that will hopefully get bundled eventually, and while making the patches I noticed in testing that ullage is either bugged or not very realistic. 

![screenshot7](https://user-images.githubusercontent.com/29461006/62508567-bd159e00-b7cd-11e9-90d3-19b3c18a9fff.png)
Under LEM RCS power (which was used in real life to perform the ullage burn before igniting the descent stage), propellant still reads as being unstable.

![screenshot8](https://user-images.githubusercontent.com/29461006/62508558-b7b85380-b7cd-11e9-9091-ca20662b8255.png)
While trying to ignite a Titan core inflight, with thrust from the boosters, the propellant was also reading as unstable. This confused me as the force from the SRBs is quite high and yet did not seem to make the engine safe to light.

I am not sure if this is intended behavior, incorrect syntax in the patches, or a bug in the mod. If it is working as intended, it would be nice for ullage force needed for stability to be defined in part configs or through a slider in settings.

**Comment by blowfishpro** [comment]
To add to this a bit, settling propellant in the tanks should only require a very small amount of acceleration.  Many upper stages do this with tiny RCS thrusters, and even larger 2nd stages often only have small solids to hold the propellant down during engine ignition.
